### ISSUE TITLE
Issues with prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by ynamite** [barvian/fluid-tailwind#24]
Fluid-Tailwind seems to have issues running together with prettier-plugin-tailwindcss.
Not a huge issue, but would be nice if they worked together.

When using them together, I keep getting the error message
```
["ERROR" - 14:04:04] Error formatting document.
["ERROR" - 14:04:04] fluid-tailwind: Fluid extractor not found in your Tailwind config
FluidError: fluid-tailwind: Fluid extractor not found in your Tailwind config
    at _class.fromCode (~/test/node_modules/fluid-tailwind/dist/index.js:114:12)
    at error (~/test/node_modules/fluid-tailwind/dist/index.js:118:20)
    at fluidPlugin (~/test/node_modules/fluid-tailwind/dist/index.js:621:7)
    at Object.assign (~/test/node_modules/fluid-tailwind/dist/index.js:816:28)
    at registerPlugins (~/test/node_modules/tailwindcss/lib/lib/setupContextUtils.js:815:61)
    at createContext (~/test/node_modules/tailwindcss/lib/lib/setupContextUtils.js:1221:5)
    at GJ (file://~/test/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:40846)
    at async d2 (file://~/test/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:39965)
    at async Object.parse (file://~/test/node_modules/prettier-plugin-tailwindcss/dist/index.mjs:2353:46860)
    at async parse4 (file://~/test/node_modules/prettier/index.mjs:22117:11)
["INFO" - 14:04:04] Formatting completed in 242ms.
```

Everything works fine once prettier-plugin-tailwindcss is disabled.

**Comment by ynamite** [comment]
By the way, do you know if the prettier class sorter works fine with fluid?

**Comment by barvian** [comment]
Should be fixed in v0.3.8 (it warns instead of erroring now). Also, I'm not sure how the Prettier plugin sorts third-party plugins but I've used it with `fluid-tailwind` on a couple sites with no issues (monorepo setups must've prevented this error from showing up) 👍🏻

**Comment by ynamite** [comment]
Thanks!

**Comment by ynamite** [comment]
Works great now, thanks again for the super fast fix!
