### ISSUE TITLE
Plugin is broken ?

### ISSUE THREAD

**Issue by RFillion** [barvian/fluid-tailwind#26]
I get this in my console : 

```
/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/fluid-tailwind/dist/index.js:15097
const toPrecision = (num, precision) => (formatters[precision] ??= new Intl.NumberFormat('en-US', {
                                                               ^^^

SyntaxError: Unexpected token '??='
    at new Script (vm.js:102:7)
    at createScript (vm.js:262:10)
    at Object.runInThisContext (vm.js:310:10)
    at evalModule (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/jiti/dist/jiti.js:1:256254)
    at jiti (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/jiti/dist/jiti.js:1:254371)
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/tailwind.config.js:3:22
    at evalModule (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/jiti/dist/jiti.js:1:254371)
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/tailwindcss/lib/lib/load-config.js:52:30
    at loadConfig (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/tailwindcss/lib/lib/load-config.js:54:6)
```

When fixing these issues, I get this : 

```
TypeError: decl.value.replaceAll is not a function
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/fluid-tailwind/dist/index.js:15222:33
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:347:18
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:299:18
    at Rule.each (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:53:16)
    at Rule.walk (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:296:17)
    at /Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:304:24
    at Root.each (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:53:16)
    at Root.walk (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:296:17)
    at Root.walkDecls (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/postcss/lib/container.js:345:19)
    at rewrite (/Applications/MAMP/htdocs/testmoduli/wp-content/themes/testmoduli/node_modules/fluid-tailwind/dist/index.js:15221:15) {
  postcssNode: Declaration {
    raws: {},
    type: 'decl',
    prop: 'position',
    value: 'relative',
    parent: Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      selector: '.relative',
      lastEach: 5,
      indexes: [Object],
      parent: [Root],
      [Symbol(isClean)]: false,
      [Symbol(my)]: true
    },
    [Symbol(isClean)]: false,
    [Symbol(my)]: true
  }
}
```

Is it broken only for me ?

**Comment by barvian** [comment]
Which version of Node are you running?

**Comment by RFillion** [comment]
Sorry for the long reply!

**Comment by barvian** [comment]
No worries! It looks like Node 14 doesn't support these features (https://node.green/). Would it be possible for you to upgrade to i.e. Node 20 (LTS)?
